# BirdSet evaluation

Evaluates DSA (DT, MT, LT) and SSA (LT) on the eight BirdSet downstream tasks, three seeds each, using the checkpoints from the v1.0 release.

## Install requirements

In [ ]:
# !pip install -r ../requirements.txt

In [2]:
import sys
sys.path.append('../')
import os
import tarfile
import urllib.request

import numpy as np
import pandas as pd
import torch

from registry import DT, MT, LT, LT_SSA
from sa4birds.evaluation import load_model, get_test_loader, test

DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'

# The eight BirdSet downstream tasks, in the order of the paper's tables
DOWN_TASKS = ["HSN", "POW", "NES", "NBP", "UHH", "SNE", "SSW", "PER"]

# Per-seed results, filled in by the evaluation cells below:
# RESULTS[model][task][metric] -> [seed 1, seed 2, seed 3]
RESULTS = {}

/path/to/sa4birds/venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Download checkpoints

In [3]:
# Checkpoints are GitHub release assets; each archive extracts to the paths in registry.py.
BASE = "https://github.com/jab2026/sa4birds/releases/download/v1.0"
ROOT = ".."

ASSETS = {f"DT-{task}": DT[task] for task in DOWN_TASKS}
ASSETS.update({"MT": MT["ALL"], "LT-DSA": LT["ALL"], "LT-SSA": LT_SSA["ALL"]})

def present(paths):
    return all(os.path.exists(f"{ROOT}/{p}/models/model.pth") for p in paths)

for asset, paths in ASSETS.items():
    if present(paths):
        print(f"sa4birds-{asset}.tar: already extracted")
        continue
    archive = f"{ROOT}/sa4birds-{asset}.tar"
    print(f"sa4birds-{asset}.tar: downloading ...")
    urllib.request.urlretrieve(f"{BASE}/sa4birds-{asset}.tar", archive)
    with tarfile.open(archive) as tar:
        tar.extractall(ROOT)
    os.remove(archive)
    assert present(paths), asset

sa4birds-DT-HSN.tar: downloading ...
sa4birds-DT-POW.tar: downloading ...
sa4birds-DT-NES.tar: downloading ...
sa4birds-DT-NBP.tar: downloading ...
sa4birds-DT-UHH.tar: downloading ...
sa4birds-DT-SNE.tar: downloading ...
sa4birds-DT-SSW.tar: downloading ...
sa4birds-DT-PER.tar: downloading ...
sa4birds-MT.tar: downloading ...
sa4birds-LT-DSA.tar: downloading ...
sa4birds-LT-SSA.tar: downloading ...

## Evaluation function

In [4]:
def run_testing(regime, device='cuda'):
    """Evaluate every seed of a regime on every task; returns {task: {metric: [per seed]}}."""
    results = {}
    for down_task in DOWN_TASKS:

        # DT has one entry per task; MT and LT share one set of checkpoints for all tasks
        ckpts = regime.get(down_task) or regime['ALL']

        models = []
        configs = []

        # ---------------------------------------------------------
        # Load models and their configs from checkpoints
        # ---------------------------------------------------------
        for ckpt in ckpts:
            m, cfg = load_model('../' + ckpt, device=device)
            models.append(m)
            # 7 s input windows; the centre 5 s is scored
            cfg.frontend.val_target_length = 701
            cfg.event_decoder.val.extracted_interval = 7
            # Set dataset name to current downstream task
            cfg.train.dataset_name = down_task
            configs.append(cfg)

        # Create test dataloader using the first config
        val_loader, class_names = get_test_loader(configs[0])

        # Map class names to label IDs using the config label map
        label2id = {k: v for k, v in configs[0].train.label_map.items()}

        # Only test on classes relevant for the current dataset
        relevant = [label2id[c] for c in class_names]

        # One value per checkpoint (seed)
        metrics = {"auroc": [], "cmap": [], "top1_acc": []}

        # ---------------------------------------------------------
        # test each model on the test dataset
        # ---------------------------------------------------------
        for model in models:
            auroc, cmap, top1_acc = test(model, val_loader, relevant, device=device)
            metrics["auroc"].append(float(auroc))
            metrics["cmap"].append(float(cmap))
            metrics["top1_acc"].append(float(top1_acc))

        results[down_task] = metrics
        print(down_task, {key: round(float(np.mean(values)), 4) for key, values in metrics.items()})
    return results

## DSA, dedicated training (DT)

In [5]:
RESULTS["DSA (DT)"] = run_testing(DT, device=DEVICE)

Testing: 100%|██████████| 94/94 [00:45<00:00,  2.07it/s]
Testing: 100%|██████████| 94/94 [00:46<00:00,  2.02it/s]
Testing: 100%|██████████| 94/94 [00:46<00:00,  2.02it/s]
HSN {'auroc': 0.956, 'cmap': 0.5793, 'top1_acc': 0.7324}
Testing: 100%|██████████| 36/36 [00:23<00:00,  1.53it/s]
Testing: 100%|██████████| 36/36 [00:23<00:00,  1.51it/s]
Testing: 100%|██████████| 36/36 [00:23<00:00,  1.54it/s]
POW {'auroc': 0.9412, 'cmap': 0.6017, 'top1_acc': 0.9456}
Testing: 100%|██████████| 192/192 [01:30<00:00,  2.13it/s]
Testing: 100%|██████████| 192/192 [01:30<00:00,  2.13it/s]
Testing: 100%|██████████| 192/192 [01:29<00:00,  2.15it/s]
NES {'auroc': 0.9218, 'cmap': 0.4121, 'top1_acc': 0.5847}
Testing: 100%|██████████| 5/5 [00:04<00:00,  1.12it/s]
Testing: 100%|██████████| 5/5 [00:04<00:00,  1.15it/s]
Testing: 100%|██████████| 5/5 [00:04<00:00,  1.13it/s]
NBP {'auroc': 0.9271, 'cmap': 0.7104, 'top1_acc': 0.7032}
Testing: 100%|██████████| 287/287 [02:04<00:00,  2.31it/s]
Testing: 100%|██████████| 287/287 [02:06<00:00,  2.26it/s]
Testing: 100%|██████████| 287/287 [02:08<00:00,  2.23it/s]
UHH {'auroc': 0.8809, 'cmap': 0.3454, 'top1_acc': 0.6784}
Testing: 100%|██████████| 186/186 [01:24<00:00,  2.19it/s]
Testing: 100%|██████████| 186/186 [01:24<00:00,  2.19it/s]
Testing: 100%|██████████| 186/186 [01:25<00:00,  2.17it/s]
SNE {'auroc': 0.8979, 'cmap': 0.4196, 'top1_acc': 0.8054}
Testing: 100%|██████████| 1604/1604 [11:08<00:00,  2.40it/s]
Testing: 100%|██████████| 1604/1604 [10:46<00:00,  2.48it/s]
Testing: 100%|██████████| 1604/1604 [10:48<00:00,  2.47it/s]
SSW {'auroc': 0.9761, 'cmap': 0.517, 'top1_acc': 0.7825}
Testing: 100%|██████████| 119/119 [00:58<00:00,  2.04it/s]
Testing: 100%|██████████| 119/119 [00:57<00:00,  2.06it/s]
Testing: 100%|██████████| 119/119 [00:54<00:00,  2.19it/s]
PER {'auroc': 0.8122, 'cmap': 0.3474, 'top1_acc': 0.6829}

Map: 100%|██████████| 12000/12000 [00:00<00:00, 34795.25 examples/s]
Map: 100%|██████████| 4560/4560 [00:00<00:00, 33640.72 examples/s]
Map: 100%|██████████| 4560/4560 [00:02<00:00, 1685.75 examples/s]
Map: 100%|██████████| 24480/24480 [00:00<00:00, 33565.12 examples/s]
Map: 100%|██████████| 24480/24480 [00:05<00:00, 4519.29 examples/s]
Map: 100%|██████████| 539/539 [00:00<00:00, 39445.32 examples/s]
Map: 100%|██████████| 539/539 [00:00<00:00, 18494.80 examples/s]
Map: 100%|██████████| 36637/36637 [00:01<00:00, 33571.92 examples/s]
Map: 100%|██████████| 36637/36637 [00:55<00:00, 663.62 examples/s]
Map: 100%|██████████| 23756/23756 [00:00<00:00, 33755.97 examples/s]
Map: 100%|██████████| 23756/23756 [00:14<00:00, 1664.54 examples/s]
Map: 100%|██████████| 205200/205200 [00:06<00:00, 33965.46 examples/s]
Map: 100%|██████████| 205200/205200 [04:15<00:00, 802.89 examples/s]
Map: 100%|██████████| 15120/15120 [00:00<00:00, 27833.50 examples/s]
Map: 100%|██████████| 15120/15120 [00:07<00:00, 2129.87 examples/s]

## DSA, medium training (MT)

In [6]:
RESULTS["DSA (MT)"] = run_testing(MT, device=DEVICE)

Testing: 100%|██████████| 94/94 [00:46<00:00,  2.03it/s]
Testing: 100%|██████████| 94/94 [00:45<00:00,  2.06it/s]
Testing: 100%|██████████| 94/94 [00:45<00:00,  2.06it/s]
HSN {'auroc': 0.9155, 'cmap': 0.5554, 'top1_acc': 0.7049}
Testing: 100%|██████████| 36/36 [00:23<00:00,  1.53it/s]
Testing: 100%|██████████| 36/36 [00:24<00:00,  1.48it/s]
Testing: 100%|██████████| 36/36 [00:22<00:00,  1.60it/s]
POW {'auroc': 0.9374, 'cmap': 0.5399, 'top1_acc': 0.9149}
Testing: 100%|██████████| 192/192 [01:28<00:00,  2.18it/s]
Testing: 100%|██████████| 192/192 [01:26<00:00,  2.21it/s]
Testing: 100%|██████████| 192/192 [01:28<00:00,  2.17it/s]
NES {'auroc': 0.9341, 'cmap': 0.3935, 'top1_acc': 0.5774}
Testing: 100%|██████████| 5/5 [00:04<00:00,  1.13it/s]
Testing: 100%|██████████| 5/5 [00:04<00:00,  1.13it/s]
Testing: 100%|██████████| 5/5 [00:04<00:00,  1.15it/s]
NBP {'auroc': 0.9356, 'cmap': 0.6891, 'top1_acc': 0.7069}
Testing: 100%|██████████| 287/287 [02:04<00:00,  2.31it/s]
Testing: 100%|██████████| 287/287 [02:03<00:00,  2.32it/s]
Testing: 100%|██████████| 287/287 [02:04<00:00,  2.31it/s]
UHH {'auroc': 0.8794, 'cmap': 0.3408, 'top1_acc': 0.7133}
Testing: 100%|██████████| 186/186 [01:22<00:00,  2.25it/s]
Testing: 100%|██████████| 186/186 [01:22<00:00,  2.27it/s]
Testing: 100%|██████████| 186/186 [01:21<00:00,  2.28it/s]
SNE {'auroc': 0.8917, 'cmap': 0.4014, 'top1_acc': 0.8126}
Testing: 100%|██████████| 1604/1604 [10:49<00:00,  2.47it/s]
Testing: 100%|██████████| 1604/1604 [10:50<00:00,  2.47it/s]
Testing: 100%|██████████| 1604/1604 [10:43<00:00,  2.49it/s]
SSW {'auroc': 0.9742, 'cmap': 0.4823, 'top1_acc': 0.7559}
Testing: 100%|██████████| 119/119 [00:53<00:00,  2.21it/s]
Testing: 100%|██████████| 119/119 [00:53<00:00,  2.23it/s]
Testing: 100%|██████████| 119/119 [00:53<00:00,  2.21it/s]
PER {'auroc': 0.8092, 'cmap': 0.3246, 'top1_acc': 0.6577}

Map: 100%|██████████| 12000/12000 [00:00<00:00, 35079.33 examples/s]
Map: 100%|██████████| 12000/12000 [00:03<00:00, 3251.57 examples/s]
Map: 100%|██████████| 4560/4560 [00:00<00:00, 34121.45 examples/s]
Map: 100%|██████████| 4560/4560 [00:02<00:00, 1666.04 examples/s]
Map: 100%|██████████| 24480/24480 [00:00<00:00, 33372.61 examples/s]
Map: 100%|██████████| 24480/24480 [00:05<00:00, 4642.20 examples/s]
Map: 100%|██████████| 539/539 [00:00<00:00, 39613.28 examples/s]
Map: 100%|██████████| 539/539 [00:00<00:00, 18460.51 examples/s]
Map: 100%|██████████| 36637/36637 [00:01<00:00, 33922.96 examples/s]
Map: 100%|██████████| 36637/36637 [00:54<00:00, 667.78 examples/s]
Map: 100%|██████████| 23756/23756 [00:00<00:00, 34418.30 examples/s]
Map: 100%|██████████| 23756/23756 [00:14<00:00, 1662.06 examples/s]
Map: 100%|██████████| 205200/205200 [00:05<00:00, 34715.27 examples/s]
Map: 100%|██████████| 205200/205200 [04:12<00:00, 813.30 examples/s]
Map: 100%|██████████| 15120/15120 [00:00<00:00, 32418.75 examples/s]
Map: 100%|██████████| 15120/15120 [00:06<00:00, 2174.40 examples/s]

## DSA, large training (LT)

In [7]:
RESULTS["DSA (LT)"] = run_testing(LT, device=DEVICE)

Testing: 100%|██████████| 94/94 [00:49<00:00,  1.89it/s]
Testing: 100%|██████████| 94/94 [00:51<00:00,  1.82it/s]
Testing: 100%|██████████| 94/94 [00:52<00:00,  1.80it/s]
HSN {'auroc': 0.9309, 'cmap': 0.5703, 'top1_acc': 0.7145}
Testing: 100%|██████████| 36/36 [00:24<00:00,  1.45it/s]
Testing: 100%|██████████| 36/36 [00:24<00:00,  1.48it/s]
Testing: 100%|██████████| 36/36 [00:22<00:00,  1.63it/s]
POW {'auroc': 0.9001, 'cmap': 0.5197, 'top1_acc': 0.9368}
Testing: 100%|██████████| 192/192 [01:42<00:00,  1.87it/s]
Testing: 100%|██████████| 192/192 [01:41<00:00,  1.89it/s]
Testing: 100%|██████████| 192/192 [01:43<00:00,  1.86it/s]
NES {'auroc': 0.9493, 'cmap': 0.3947, 'top1_acc': 0.5839}
Testing: 100%|██████████| 5/5 [00:04<00:00,  1.11it/s]
Testing: 100%|██████████| 5/5 [00:04<00:00,  1.11it/s]
Testing: 100%|██████████| 5/5 [00:04<00:00,  1.11it/s]
NBP {'auroc': 0.9314, 'cmap': 0.6992, 'top1_acc': 0.7236}
Testing: 100%|██████████| 287/287 [02:28<00:00,  1.94it/s]
Testing: 100%|██████████| 287/287 [02:29<00:00,  1.92it/s]
Testing: 100%|██████████| 287/287 [02:27<00:00,  1.95it/s]
UHH {'auroc': 0.9061, 'cmap': 0.33, 'top1_acc': 0.7272}
Testing: 100%|██████████| 186/186 [01:37<00:00,  1.91it/s]
Testing: 100%|██████████| 186/186 [01:38<00:00,  1.90it/s]
Testing: 100%|██████████| 186/186 [01:38<00:00,  1.90it/s]
SNE {'auroc': 0.8722, 'cmap': 0.3777, 'top1_acc': 0.8218}
Testing: 100%|██████████| 1604/1604 [13:31<00:00,  1.98it/s]
Testing: 100%|██████████| 1604/1604 [13:32<00:00,  1.98it/s]
Testing: 100%|██████████| 1604/1604 [13:33<00:00,  1.97it/s]
SSW {'auroc': 0.9705, 'cmap': 0.4679, 'top1_acc': 0.7697}
Testing: 100%|██████████| 119/119 [01:03<00:00,  1.86it/s]
Testing: 100%|██████████| 119/119 [01:04<00:00,  1.84it/s]
Testing: 100%|██████████| 119/119 [01:02<00:00,  1.90it/s]
PER {'auroc': 0.7974, 'cmap': 0.3152, 'top1_acc': 0.6314}

Map: 100%|██████████| 12000/12000 [00:00<00:00, 35177.20 examples/s]
Map: 100%|██████████| 12000/12000 [00:03<00:00, 3272.41 examples/s]
Map: 100%|██████████| 4560/4560 [00:00<00:00, 34259.46 examples/s]
Map: 100%|██████████| 4560/4560 [00:02<00:00, 1709.47 examples/s]
Map: 100%|██████████| 24480/24480 [00:00<00:00, 34605.52 examples/s]
Map: 100%|██████████| 24480/24480 [00:05<00:00, 4683.24 examples/s]
Map: 100%|██████████| 539/539 [00:00<00:00, 36547.09 examples/s]
Map: 100%|██████████| 539/539 [00:00<00:00, 17946.57 examples/s]
Map: 100%|██████████| 36637/36637 [00:01<00:00, 34589.03 examples/s]
Map: 100%|██████████| 36637/36637 [00:54<00:00, 675.56 examples/s]
Map: 100%|██████████| 23756/23756 [00:00<00:00, 34759.38 examples/s]
Map: 100%|██████████| 23756/23756 [00:14<00:00, 1667.05 examples/s]
Map: 100%|██████████| 205200/205200 [00:05<00:00, 34690.79 examples/s]
Map: 100%|██████████| 205200/205200 [04:12<00:00, 813.73 examples/s]
Map: 100%|██████████| 15120/15120 [00:00<00:00, 32753.60 examples/s]
Map: 100%|██████████| 15120/15120 [00:06<00:00, 2198.87 examples/s]

## SSA, large training (LT)

In [8]:
RESULTS["SSA (LT)"] = run_testing(LT_SSA, device=DEVICE)

Testing: 100%|██████████| 94/94 [00:44<00:00,  2.11it/s]
Testing: 100%|██████████| 94/94 [00:45<00:00,  2.06it/s]
Testing: 100%|██████████| 94/94 [00:45<00:00,  2.06it/s]
HSN {'auroc': 0.9294, 'cmap': 0.5708, 'top1_acc': 0.7151}
Testing: 100%|██████████| 36/36 [00:22<00:00,  1.58it/s]
Testing: 100%|██████████| 36/36 [00:21<00:00,  1.70it/s]
Testing: 100%|██████████| 36/36 [00:22<00:00,  1.61it/s]
POW {'auroc': 0.9001, 'cmap': 0.5198, 'top1_acc': 0.9367}
Testing: 100%|██████████| 192/192 [01:26<00:00,  2.21it/s]
Testing: 100%|██████████| 192/192 [01:27<00:00,  2.18it/s]
Testing: 100%|██████████| 192/192 [01:28<00:00,  2.18it/s]
NES {'auroc': 0.9493, 'cmap': 0.394, 'top1_acc': 0.5839}
Testing: 100%|██████████| 5/5 [00:04<00:00,  1.17it/s]
Testing: 100%|██████████| 5/5 [00:04<00:00,  1.19it/s]
Testing: 100%|██████████| 5/5 [00:04<00:00,  1.19it/s]
NBP {'auroc': 0.9318, 'cmap': 0.6987, 'top1_acc': 0.7254}
Testing: 100%|██████████| 287/287 [02:07<00:00,  2.25it/s]
Testing: 100%|██████████| 287/287 [02:07<00:00,  2.25it/s]
Testing: 100%|██████████| 287/287 [02:06<00:00,  2.27it/s]
UHH {'auroc': 0.9071, 'cmap': 0.3296, 'top1_acc': 0.7278}
Testing: 100%|██████████| 186/186 [01:24<00:00,  2.19it/s]
Testing: 100%|██████████| 186/186 [01:25<00:00,  2.18it/s]
Testing: 100%|██████████| 186/186 [01:24<00:00,  2.21it/s]
SNE {'auroc': 0.8724, 'cmap': 0.3778, 'top1_acc': 0.8223}
Testing: 100%|██████████| 1604/1604 [11:54<00:00,  2.25it/s]
Testing: 100%|██████████| 1604/1604 [11:40<00:00,  2.29it/s]
Testing: 100%|██████████| 1604/1604 [11:37<00:00,  2.30it/s]
SSW {'auroc': 0.9708, 'cmap': 0.4689, 'top1_acc': 0.7698}
Testing: 100%|██████████| 119/119 [00:55<00:00,  2.16it/s]
Testing: 100%|██████████| 119/119 [00:55<00:00,  2.16it/s]
Testing: 100%|██████████| 119/119 [00:55<00:00,  2.13it/s]
PER {'auroc': 0.7976, 'cmap': 0.3152, 'top1_acc': 0.6327}

Map: 100%|██████████| 12000/12000 [00:00<00:00, 34986.09 examples/s]
Map: 100%|██████████| 12000/12000 [00:03<00:00, 3310.57 examples/s]
Map: 100%|██████████| 4560/4560 [00:00<00:00, 34159.72 examples/s]
Map: 100%|██████████| 4560/4560 [00:02<00:00, 1710.15 examples/s]
Map: 100%|██████████| 24480/24480 [00:00<00:00, 34584.12 examples/s]
Map: 100%|██████████| 24480/24480 [00:05<00:00, 4676.35 examples/s]
Map: 100%|██████████| 539/539 [00:00<00:00, 36838.30 examples/s]
Map: 100%|██████████| 539/539 [00:00<00:00, 18674.46 examples/s]
Map: 100%|██████████| 36637/36637 [00:01<00:00, 34820.49 examples/s]
Map: 100%|██████████| 36637/36637 [00:54<00:00, 672.32 examples/s]
Map: 100%|██████████| 23756/23756 [00:00<00:00, 34204.90 examples/s]
Map: 100%|██████████| 23756/23756 [00:14<00:00, 1671.65 examples/s]
Map: 100%|██████████| 205200/205200 [00:06<00:00, 33563.06 examples/s]
Map: 100%|██████████| 205200/205200 [04:14<00:00, 807.57 examples/s]
Map: 100%|██████████| 15120/15120 [00:00<00:00, 31593.73 examples/s]
Map: 100%|██████████| 15120/15120 [00:07<00:00, 2150.82 examples/s]

## Results

Mean over the three seeds for each model and task; the Mean column averages the eight tasks.

### AUROC

In [9]:
def results_table(metric):
    """Mean over the three seeds per model and task; Mean = the eight-task average."""
    rows = {}
    for model, per_task in RESULTS.items():
        seeds = np.array([per_task[task][metric] for task in DOWN_TASKS])   # tasks x seeds
        rows[model] = list(seeds.mean(axis=1)) + [seeds.mean(axis=0).mean()]
    return pd.DataFrame(rows, index=DOWN_TASKS + ["Mean"]).T.round(3)

results_table("auroc")

            HSN    POW    NES    NBP    UHH    SNE    SSW    PER   Mean
DSA (DT)  0.956  0.941  0.922  0.927  0.881  0.898  0.976  0.812  0.914
DSA (MT)  0.916  0.937  0.934  0.936  0.879  0.892  0.974  0.809  0.910
DSA (LT)  0.931  0.900  0.949  0.931  0.906  0.872  0.971  0.797  0.907
SSA (LT)  0.929  0.900  0.949  0.932  0.907  0.872  0.971  0.798  0.907

### cmAP

In [10]:
results_table("cmap")

            HSN    POW    NES    NBP    UHH    SNE    SSW    PER   Mean
DSA (DT)  0.579  0.602  0.412  0.710  0.345  0.420  0.517  0.347  0.492
DSA (MT)  0.555  0.540  0.393  0.689  0.341  0.401  0.482  0.325  0.466
DSA (LT)  0.570  0.520  0.395  0.699  0.330  0.378  0.468  0.315  0.459
SSA (LT)  0.571  0.520  0.394  0.699  0.330  0.378  0.469  0.315  0.459

### Top-1 accuracy (T1-Acc)

In [11]:
results_table("top1_acc")

            HSN    POW    NES    NBP    UHH    SNE    SSW    PER   Mean
DSA (DT)  0.732  0.946  0.585  0.703  0.678  0.805  0.782  0.683  0.739
DSA (MT)  0.705  0.915  0.577  0.707  0.713  0.813  0.756  0.658  0.730
DSA (LT)  0.714  0.937  0.584  0.724  0.727  0.822  0.770  0.631  0.739
SSA (LT)  0.715  0.937  0.584  0.725  0.728  0.822  0.770  0.633  0.739