# Ablation study

Evaluates the classifier heads on HSN, POW, NES and UHH, and the secondary-label, test-window and data-augmentation ablations on HSN, three seeds each, using the checkpoints from the v1.0 release.

## Install requirements

In [ ]:
# !pip install -r ../requirements.txt

In [2]:
import sys
sys.path.append('../')
import glob
import os
import tarfile
import urllib.request

import numpy as np
import pandas as pd
import torch

from registry import DT
from sa4birds.evaluation import load_model, get_test_loader, test

DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'

# Classifier heads are compared on four BirdSet tasks; the other ablations on HSN only
HEAD_TASKS = ["HSN", "POW", "NES", "UHH"]
HEAD_VARIANTS = ["linear_head", "time_attention_head", "ssa_head"]
HSN_VARIANTS = ["no_secondary_labels", "aug_none", "aug_signal_mixup", "aug_bg_noise",
                "aug_colored_noise_gain", "aug_no_call"]

# Per-seed results, filled in by the evaluation cells below:
# HEAD_RESULTS[head][task][metric] and RESULTS[name][metric] -> [seed 1, seed 2, seed 3]
HEAD_RESULTS = {}
RESULTS = {}

/path/to/sa4birds/venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Download checkpoints

In [3]:
# Checkpoints are GitHub release assets. The full model (DSA, dedicated training) comes
# from sa4birds-DT-<TASK>.tar; the other heads from sa4birds-ablation-<head>-<TASK>.tar;
# the HSN-only ablations from sa4birds-ablation-<variant>.tar. Each archive extracts to
# ckpts/DT/<TASK>/ or ckpts/ablation/<variant>/<head>_<TASK>_seed{1,2,3}/.
BASE = "https://github.com/jab2026/sa4birds/releases/download/v1.0"
ROOT = ".."

def seed_dirs(variant, task="HSN"):
    return sorted(glob.glob(f"{ROOT}/ckpts/ablation/{variant}/*_{task}_seed*"))

def dsa_dirs(task):
    return [f"{ROOT}/{p}" for p in DT[task]]

ASSETS = {f"DT-{t}": (lambda t=t: dsa_dirs(t)) for t in HEAD_TASKS}
ASSETS.update({f"ablation-{v}-{t}": (lambda v=v, t=t: seed_dirs(v, t))
               for v in HEAD_VARIANTS for t in HEAD_TASKS})
ASSETS.update({f"ablation-{v}": (lambda v=v: seed_dirs(v)) for v in HSN_VARIANTS})

def present(paths):
    return len(paths) == 3 and all(os.path.exists(f"{p}/models/model.pth") for p in paths)

for asset, paths in ASSETS.items():
    if present(paths()):
        print(f"sa4birds-{asset}.tar: already extracted")
        continue
    archive = f"{ROOT}/sa4birds-{asset}.tar"
    print(f"sa4birds-{asset}.tar: downloading ...")
    urllib.request.urlretrieve(f"{BASE}/sa4birds-{asset}.tar", archive)
    with tarfile.open(archive) as tar:
        tar.extractall(ROOT)
    os.remove(archive)
    assert present(paths()), asset

sa4birds-DT-HSN.tar: downloading ...
sa4birds-DT-POW.tar: downloading ...
sa4birds-DT-NES.tar: downloading ...
sa4birds-DT-UHH.tar: downloading ...
sa4birds-ablation-linear_head-HSN.tar: downloading ...
sa4birds-ablation-linear_head-POW.tar: downloading ...
sa4birds-ablation-linear_head-NES.tar: downloading ...
sa4birds-ablation-linear_head-UHH.tar: downloading ...
sa4birds-ablation-time_attention_head-HSN.tar: downloading ...
sa4birds-ablation-time_attention_head-POW.tar: downloading ...
sa4birds-ablation-time_attention_head-NES.tar: downloading ...
sa4birds-ablation-time_attention_head-UHH.tar: downloading ...
sa4birds-ablation-ssa_head-HSN.tar: downloading ...
sa4birds-ablation-ssa_head-POW.tar: downloading ...
sa4birds-ablation-ssa_head-NES.tar: downloading ...
sa4birds-ablation-ssa_head-UHH.tar: downloading ...
sa4birds-ablation-no_secondary_labels.tar: downloading ...
sa4birds-ablation-aug_none.tar: downloading ...
sa4birds-ablation-aug_signal_mixup.tar: downloading ...
sa4birds-ablation-aug_bg_noise.tar: downloading ...
sa4birds-ablation-aug_colored_noise_gain.tar: downloading ...
sa4birds-ablation-aug_no_call.tar: downloading ...

## Evaluation function

In [4]:
def run_testing(ckpts, task="HSN", extracted_interval=7, target_length=701, device='cuda'):
    """Evaluate every seed on one task; returns {metric: [per seed]}.

    extracted_interval / target_length set the test window: 7 s (701 frames) with
    the centre 5 s scored, or the plain 5 s segments (501 frames).
    """
    models = []
    configs = []

    # ---------------------------------------------------------
    # Load models and their configs from checkpoints
    # ---------------------------------------------------------
    for ckpt in ckpts:
        m, cfg = load_model(ckpt, device=device)
        models.append(m)
        # Override validation parameters for evaluation
        cfg.frontend.val_target_length = target_length
        cfg.event_decoder.val.extracted_interval = extracted_interval
        cfg.train.dataset_name = task
        configs.append(cfg)

    # Create test dataloader using the first config
    val_loader, class_names = get_test_loader(configs[0])

    # Only test on classes relevant for the current dataset
    label2id = {k: v for k, v in configs[0].train.label_map.items()}
    relevant = [label2id[c] for c in class_names]

    # One value per checkpoint (seed)
    metrics = {"auroc": [], "cmap": [], "top1_acc": []}
    for model in models:
        auroc, cmap, top1_acc = test(model, val_loader, relevant, device=device)
        metrics["auroc"].append(float(auroc))
        metrics["cmap"].append(float(cmap))
        metrics["top1_acc"].append(float(top1_acc))

    print(task, {key: round(float(np.mean(values)), 4) for key, values in metrics.items()})
    return metrics

## 1. Classifier heads

The full model (DSA) and three alternative heads, all on the same encoder and training recipe, on HSN, POW, NES and UHH. The linear head is tested on 5 s windows; the attention heads use a 7 s window and score its centre 5 s.

In [5]:
# DSA: the full model (dedicated training); its HSN result is the reference in the other ablations
HEAD_RESULTS["DSA"] = {t: run_testing(dsa_dirs(t), task=t, device=DEVICE) for t in HEAD_TASKS}
RESULTS["dsa"] = HEAD_RESULTS["DSA"]["HSN"]

Testing: 100%|██████████| 94/94 [00:45<00:00,  2.09it/s]
Testing: 100%|██████████| 94/94 [00:45<00:00,  2.06it/s]
Testing: 100%|██████████| 94/94 [00:45<00:00,  2.06it/s]
HSN {'auroc': 0.956, 'cmap': 0.5793, 'top1_acc': 0.7324}
Testing: 100%|██████████| 36/36 [00:22<00:00,  1.57it/s]
Testing: 100%|██████████| 36/36 [00:22<00:00,  1.61it/s]
Testing: 100%|██████████| 36/36 [00:22<00:00,  1.59it/s]
POW {'auroc': 0.9412, 'cmap': 0.6017, 'top1_acc': 0.9456}
Testing: 100%|██████████| 192/192 [01:28<00:00,  2.16it/s]
Testing: 100%|██████████| 192/192 [01:28<00:00,  2.17it/s]
Testing: 100%|██████████| 192/192 [01:27<00:00,  2.20it/s]
NES {'auroc': 0.9218, 'cmap': 0.4121, 'top1_acc': 0.5847}
Testing: 100%|██████████| 287/287 [02:02<00:00,  2.34it/s]
Testing: 100%|██████████| 287/287 [02:02<00:00,  2.34it/s]
Testing: 100%|██████████| 287/287 [02:02<00:00,  2.34it/s]
UHH {'auroc': 0.8809, 'cmap': 0.3454, 'top1_acc': 0.6784}

Map: 100%|██████████| 12000/12000 [00:00<00:00, 34841.45 examples/s]
Map: 100%|██████████| 4560/4560 [00:00<00:00, 33899.37 examples/s]
Map: 100%|██████████| 24480/24480 [00:00<00:00, 33825.92 examples/s]
Map: 100%|██████████| 36637/36637 [00:01<00:00, 34390.66 examples/s]

In [6]:
HEAD_RESULTS["Linear"] = {t: run_testing(seed_dirs("linear_head", t), task=t, extracted_interval=5,
                                           target_length=501, device=DEVICE) for t in HEAD_TASKS}

Testing: 100%|██████████| 94/94 [00:31<00:00,  3.01it/s]
Testing: 100%|██████████| 94/94 [00:30<00:00,  3.03it/s]
Testing: 100%|██████████| 94/94 [00:30<00:00,  3.04it/s]
HSN {'auroc': 0.9262, 'cmap': 0.5522, 'top1_acc': 0.6726}
Testing: 100%|██████████| 36/36 [00:16<00:00,  2.14it/s]
Testing: 100%|██████████| 36/36 [00:17<00:00,  2.07it/s]
Testing: 100%|██████████| 36/36 [00:16<00:00,  2.20it/s]
POW {'auroc': 0.9212, 'cmap': 0.5918, 'top1_acc': 0.9516}
Testing: 100%|██████████| 192/192 [00:59<00:00,  3.24it/s]
Testing: 100%|██████████| 192/192 [01:00<00:00,  3.19it/s]
Testing: 100%|██████████| 192/192 [00:59<00:00,  3.24it/s]
NES {'auroc': 0.9033, 'cmap': 0.4171, 'top1_acc': 0.5775}
Testing: 100%|██████████| 287/287 [01:24<00:00,  3.41it/s]
Testing: 100%|██████████| 287/287 [01:23<00:00,  3.42it/s]
Testing: 100%|██████████| 287/287 [01:22<00:00,  3.48it/s]
UHH {'auroc': 0.8572, 'cmap': 0.3464, 'top1_acc': 0.6775}

Map: 100%|██████████| 12000/12000 [00:00<00:00, 34537.41 examples/s]
Map: 100%|██████████| 4560/4560 [00:00<00:00, 34047.22 examples/s]
Map: 100%|██████████| 4560/4560 [00:02<00:00, 1708.17 examples/s]
Map: 100%|██████████| 24480/24480 [00:00<00:00, 33986.77 examples/s]
Map: 100%|██████████| 24480/24480 [00:05<00:00, 4570.70 examples/s]
Map: 100%|██████████| 36637/36637 [00:01<00:00, 33667.74 examples/s]
Map: 100%|██████████| 36637/36637 [00:54<00:00, 666.60 examples/s]

In [7]:
HEAD_RESULTS["Time attention"] = {t: run_testing(seed_dirs("time_attention_head", t), task=t, device=DEVICE)
                                  for t in HEAD_TASKS}

Testing: 100%|██████████| 94/94 [00:43<00:00,  2.16it/s]
Testing: 100%|██████████| 94/94 [00:44<00:00,  2.12it/s]
Testing: 100%|██████████| 94/94 [00:43<00:00,  2.14it/s]
HSN {'auroc': 0.9457, 'cmap': 0.5847, 'top1_acc': 0.7046}
Testing: 100%|██████████| 36/36 [00:17<00:00,  2.02it/s]
Testing: 100%|██████████| 36/36 [00:18<00:00,  1.92it/s]
Testing: 100%|██████████| 36/36 [00:18<00:00,  1.98it/s]
POW {'auroc': 0.9273, 'cmap': 0.6021, 'top1_acc': 0.9483}
Testing: 100%|██████████| 192/192 [01:24<00:00,  2.27it/s]
Testing: 100%|██████████| 192/192 [01:23<00:00,  2.29it/s]
Testing: 100%|██████████| 192/192 [01:24<00:00,  2.28it/s]
NES {'auroc': 0.9198, 'cmap': 0.4031, 'top1_acc': 0.5957}
Testing: 100%|██████████| 287/287 [01:59<00:00,  2.41it/s]
Testing: 100%|██████████| 287/287 [02:00<00:00,  2.38it/s]
Testing: 100%|██████████| 287/287 [01:58<00:00,  2.42it/s]
UHH {'auroc': 0.8354, 'cmap': 0.3322, 'top1_acc': 0.6555}

Map: 100%|██████████| 12000/12000 [00:00<00:00, 35214.10 examples/s]
Map: 100%|██████████| 4560/4560 [00:00<00:00, 34106.30 examples/s]
Map: 100%|██████████| 4560/4560 [00:02<00:00, 1646.21 examples/s]
Map: 100%|██████████| 24480/24480 [00:00<00:00, 33801.85 examples/s]
Map: 100%|██████████| 24480/24480 [00:05<00:00, 4632.14 examples/s]
Map: 100%|██████████| 36637/36637 [00:01<00:00, 34341.63 examples/s]
Map: 100%|██████████| 36637/36637 [00:54<00:00, 666.74 examples/s]

In [8]:
HEAD_RESULTS["SSA"] = {t: run_testing(seed_dirs("ssa_head", t), task=t, device=DEVICE) for t in HEAD_TASKS}

Testing: 100%|██████████| 94/94 [00:44<00:00,  2.12it/s]
Testing: 100%|██████████| 94/94 [00:43<00:00,  2.14it/s]
Testing: 100%|██████████| 94/94 [00:45<00:00,  2.06it/s]
HSN {'auroc': 0.9551, 'cmap': 0.5842, 'top1_acc': 0.724}
Testing: 100%|██████████| 36/36 [00:18<00:00,  1.95it/s]
Testing: 100%|██████████| 36/36 [00:17<00:00,  2.01it/s]
Testing: 100%|██████████| 36/36 [00:18<00:00,  1.99it/s]
POW {'auroc': 0.9375, 'cmap': 0.6041, 'top1_acc': 0.9446}
Testing: 100%|██████████| 192/192 [01:25<00:00,  2.25it/s]
Testing: 100%|██████████| 192/192 [01:25<00:00,  2.25it/s]
Testing: 100%|██████████| 192/192 [01:25<00:00,  2.25it/s]
NES {'auroc': 0.9183, 'cmap': 0.4145, 'top1_acc': 0.5885}
Testing: 100%|██████████| 287/287 [02:03<00:00,  2.32it/s]
Testing: 100%|██████████| 287/287 [02:00<00:00,  2.39it/s]
Testing: 100%|██████████| 287/287 [01:59<00:00,  2.40it/s]
UHH {'auroc': 0.8824, 'cmap': 0.3501, 'top1_acc': 0.6573}

Map: 100%|██████████| 12000/12000 [00:00<00:00, 34437.60 examples/s]
Map: 100%|██████████| 4560/4560 [00:00<00:00, 33632.14 examples/s]
Map: 100%|██████████| 4560/4560 [00:02<00:00, 1648.44 examples/s]
Map: 100%|██████████| 24480/24480 [00:00<00:00, 33900.96 examples/s]
Map: 100%|██████████| 24480/24480 [00:05<00:00, 4601.71 examples/s]
Map: 100%|██████████| 36637/36637 [00:01<00:00, 33697.73 examples/s]
Map: 100%|██████████| 36637/36637 [00:55<00:00, 665.95 examples/s]

## 2. Secondary labels

Training without secondary label annotations (weight 0.0); the full model uses weight 0.9.

In [9]:
RESULTS["no secondary labels"] = run_testing(seed_dirs("no_secondary_labels"), device=DEVICE)

Testing: 100%|██████████| 94/94 [00:45<00:00,  2.08it/s]
Testing: 100%|██████████| 94/94 [00:45<00:00,  2.08it/s]
Testing: 100%|██████████| 94/94 [00:43<00:00,  2.15it/s]
HSN {'auroc': 0.9503, 'cmap': 0.5624, 'top1_acc': 0.7183}

Map: 100%|██████████| 12000/12000 [00:00<00:00, 34727.70 examples/s]

## 3. Test window

The full model tested on the plain 5 s segments instead of 7 s windows.

In [10]:
RESULTS["dsa, 5 s window"] = run_testing(dsa_dirs("HSN"), extracted_interval=5, target_length=501, device=DEVICE)

Testing: 100%|██████████| 94/94 [00:33<00:00,  2.83it/s]
Testing: 100%|██████████| 94/94 [00:32<00:00,  2.90it/s]
Testing: 100%|██████████| 94/94 [00:32<00:00,  2.89it/s]
HSN {'auroc': 0.9525, 'cmap': 0.5792, 'top1_acc': 0.7189}

Map: 100%|██████████| 12000/12000 [00:00<00:00, 34310.50 examples/s]

## 4. Data augmentation

Cumulative: each variant adds one augmentation to the one before; the full model adds spectrogram mixup and SpecAugment on top.

In [11]:
RESULTS["aug: none"] = run_testing(seed_dirs("aug_none"), device=DEVICE)

Testing: 100%|██████████| 94/94 [00:44<00:00,  2.10it/s]
Testing: 100%|██████████| 94/94 [00:45<00:00,  2.06it/s]
Testing: 100%|██████████| 94/94 [00:45<00:00,  2.05it/s]
HSN {'auroc': 0.8588, 'cmap': 0.525, 'top1_acc': 0.6417}

Map: 100%|██████████| 12000/12000 [00:00<00:00, 34656.68 examples/s]

In [12]:
RESULTS["aug: + signal mixup"] = run_testing(seed_dirs("aug_signal_mixup"), device=DEVICE)

Testing: 100%|██████████| 94/94 [00:44<00:00,  2.10it/s]
Testing: 100%|██████████| 94/94 [00:45<00:00,  2.07it/s]
Testing: 100%|██████████| 94/94 [00:45<00:00,  2.05it/s]
HSN {'auroc': 0.906, 'cmap': 0.5447, 'top1_acc': 0.7146}

Map: 100%|██████████| 12000/12000 [00:00<00:00, 34342.88 examples/s]

In [13]:
RESULTS["aug: + background noise"] = run_testing(seed_dirs("aug_bg_noise"), device=DEVICE)

Testing: 100%|██████████| 94/94 [00:45<00:00,  2.04it/s]
Testing: 100%|██████████| 94/94 [00:46<00:00,  2.04it/s]
Testing: 100%|██████████| 94/94 [00:45<00:00,  2.07it/s]
HSN {'auroc': 0.9062, 'cmap': 0.5518, 'top1_acc': 0.7202}

Map: 100%|██████████| 12000/12000 [00:00<00:00, 34617.32 examples/s]

In [14]:
RESULTS["aug: + coloured noise + gain"] = run_testing(seed_dirs("aug_colored_noise_gain"), device=DEVICE)

Testing: 100%|██████████| 94/94 [00:44<00:00,  2.10it/s]
Testing: 100%|██████████| 94/94 [00:44<00:00,  2.10it/s]
Testing: 100%|██████████| 94/94 [00:44<00:00,  2.11it/s]
HSN {'auroc': 0.9116, 'cmap': 0.5519, 'top1_acc': 0.7262}

Map: 100%|██████████| 12000/12000 [00:00<00:00, 34057.23 examples/s]

In [15]:
RESULTS["aug: + no-call samples"] = run_testing(seed_dirs("aug_no_call"), device=DEVICE)

Testing: 100%|██████████| 94/94 [00:43<00:00,  2.14it/s]
Testing: 100%|██████████| 94/94 [00:44<00:00,  2.13it/s]
Testing: 100%|██████████| 94/94 [00:44<00:00,  2.13it/s]
HSN {'auroc': 0.9507, 'cmap': 0.5801, 'top1_acc': 0.7243}

Map: 100%|██████████| 12000/12000 [00:00<00:00, 35009.57 examples/s]

## Results

Mean over the three seeds.

### Classifier heads — AUROC

The Mean column averages the four tasks within each seed, then over the seeds.

In [16]:
def head_table(metric):
    """Heads x tasks for one metric; mean over the three seeds."""
    rows = {}
    for head in ["Linear", "Time attention", "DSA", "SSA"]:
        seeds = np.array([HEAD_RESULTS[head][t][metric] for t in HEAD_TASKS])   # tasks x seeds
        rows[head] = list(seeds.mean(axis=1)) + [seeds.mean(axis=0).mean()]
    return pd.DataFrame(rows, index=HEAD_TASKS + ["Mean"]).T.round(3)

head_table("auroc")

                  HSN    POW    NES    UHH   Mean
Linear          0.926  0.921  0.903  0.857  0.902
Time attention  0.946  0.927  0.920  0.835  0.907
DSA             0.956  0.941  0.922  0.881  0.925
SSA             0.955  0.937  0.918  0.882  0.923

### Classifier heads — cmAP

In [17]:
head_table("cmap")

                  HSN    POW    NES    UHH   Mean
Linear          0.552  0.592  0.417  0.346  0.477
Time attention  0.585  0.602  0.403  0.332  0.481
DSA             0.579  0.602  0.412  0.345  0.485
SSA             0.584  0.604  0.414  0.350  0.488

### Classifier heads — T1-Acc

In [18]:
head_table("top1_acc")

                  HSN    POW    NES    UHH   Mean
Linear          0.673  0.952  0.578  0.678  0.720
Time attention  0.705  0.948  0.596  0.656  0.726
DSA             0.732  0.946  0.585  0.678  0.735
SSA             0.724  0.945  0.588  0.657  0.729

### Secondary labels (HSN)

In [19]:
def results_table(rows):
    """rows: {label shown in the table: RESULTS key}; mean over the three seeds (HSN)."""
    names = {"auroc": "AUROC", "cmap": "cmAP", "top1_acc": "T1-Acc"}
    data = {label: {names[m]: np.mean(RESULTS[key][m]) for m in names} for label, key in rows.items()}
    return pd.DataFrame(data).T.round(3)

results_table({"Secondary label weight 0.0": "no secondary labels",
               "Secondary label weight 0.9": "dsa"})

                            AUROC   cmAP  T1-Acc
Secondary label weight 0.0  0.950  0.562   0.718
Secondary label weight 0.9  0.956  0.579   0.732

### Test window (HSN)

In [20]:
results_table({"5 s": "dsa, 5 s window",
               "7 s (centre 5 s scored)": "dsa"})

                         AUROC   cmAP  T1-Acc
5 s                      0.952  0.579   0.719
7 s (centre 5 s scored)  0.956  0.579   0.732

### Data augmentation (HSN, cumulative)

In [21]:
results_table({"None": "aug: none",
               "+ Mixup (signal)": "aug: + signal mixup",
               "+ Background noise": "aug: + background noise",
               "+ Coloured noise + gain": "aug: + coloured noise + gain",
               "+ No-call samples": "aug: + no-call samples",
               "+ Mixup (spectrogram) + SpecAugment": "dsa"})

                                     AUROC   cmAP  T1-Acc
None                                 0.859  0.525   0.642
+ Mixup (signal)                     0.906  0.545   0.715
+ Background noise                   0.906  0.552   0.720
+ Coloured noise + gain              0.912  0.552   0.726
+ No-call samples                    0.951  0.580   0.724
+ Mixup (spectrogram) + SpecAugment  0.956  0.579   0.732