# BEANS evaluation

Evaluates the frozen encoder with a DSA head trained per BEANS task, three seeds each, using the checkpoints from the v1.0 release.

## Install requirements

In [ ]:
# !pip install -r ../requirements.txt

In [2]:
import sys
sys.path.append('../')
import os

from sa4birds.evaluation import load_model, to_n_hot, test
import numpy as np
import glob
import tarfile
import urllib.request
import pandas as pd
from datasets import Dataset
from functools import partial
from sa4birds.utils.transform import ValTransformBeans
from sa4birds.utils.event_decoder import EventDecoder
import torch
import json

DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'

# Directory where the BEANS dataset is stored (set BEANS_ROOT or edit this line).
# To download BEANS, see: https://github.com/earthspecies/beans
BEANS_ROOT_PATH = os.environ.get("BEANS_ROOT", "<PATH TO BEANS>")

# task -> (BEANS data directory, metric reported in the paper)
TASKS = {
    "watkins":        ("watkins",             "T1-Acc"),
    "bats":           ("egyptian_fruit_bats", "T1-Acc"),
    "cbi":            ("cbi",                 "T1-Acc"),
    "dogs":           ("dogs",                "T1-Acc"),
    "humbugdb":       ("HumBugDB",            "T1-Acc"),
    "speech":         ("speech_commands",     "T1-Acc"),
    "enabirds":       ("enabirds",            "cmAP"),
    "hiceas":         ("hiceas",              "cmAP"),
    "rfcx":           ("rfcx",                "cmAP"),
    "hainan_gibbons": ("hainan_gibbons",      "cmAP"),
}

# Per-seed results, filled in by the evaluation cells below.
RESULTS = {}

/path/to/sa4birds/venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Download checkpoints

In [3]:
# Three seeds per task, published as one archive per task on the v1.0 release.
# Each archive extracts to ckpts/beans/<task>/dsa_<task>_seed{1,2,3}/.
BASE = "https://github.com/jab2026/sa4birds/releases/download/v1.0"
ROOT = ".."

def seed_dirs(task):
    return sorted(glob.glob(f"{ROOT}/ckpts/beans/{task}/dsa_{task}_seed*"))

for task in TASKS:
    if len(seed_dirs(task)) == 3:
        continue
    archive = f"{ROOT}/sa4birds-BEANS-{task}.tar"
    print(f"downloading sa4birds-BEANS-{task}.tar ...")
    urllib.request.urlretrieve(f"{BASE}/sa4birds-BEANS-{task}.tar", archive)
    with tarfile.open(archive) as tar:
        tar.extractall(ROOT)
    os.remove(archive)

for task in TASKS:
    print(f"{task:15s} {[os.path.basename(d) for d in seed_dirs(task)]}")

watkins         ['dsa_watkins_seed1', 'dsa_watkins_seed2', 'dsa_watkins_seed3']
bats            ['dsa_bats_seed1', 'dsa_bats_seed2', 'dsa_bats_seed3']
cbi             ['dsa_cbi_seed1', 'dsa_cbi_seed2', 'dsa_cbi_seed3']
dogs            ['dsa_dogs_seed1', 'dsa_dogs_seed2', 'dsa_dogs_seed3']
humbugdb        ['dsa_humbugdb_seed1', 'dsa_humbugdb_seed2', 'dsa_humbugdb_seed3']
speech          ['dsa_speech_seed1', 'dsa_speech_seed2', 'dsa_speech_seed3']
enabirds        ['dsa_enabirds_seed1', 'dsa_enabirds_seed2', 'dsa_enabirds_seed3']
hiceas          ['dsa_hiceas_seed1', 'dsa_hiceas_seed2', 'dsa_hiceas_seed3']
rfcx            ['dsa_rfcx_seed1', 'dsa_rfcx_seed2', 'dsa_rfcx_seed3']
hainan_gibbons  ['dsa_hainan_gibbons_seed1', 'dsa_hainan_gibbons_seed2', 'dsa_hainan_gibbons_seed3']

## Evaluation functions

In [4]:
def evaluate_beans_classification(ckpts, down_task, device='cuda'):
        models = []
        configs = []

        # ---------------------------------------------------------
        # Load models and their configs from checkpoints
        # ---------------------------------------------------------
        for ckpt in ckpts:
            m, cfg = load_model(ckpt, device=device)
            models.append(m)
            cfg.train.dataset_name = down_task
            configs.append(cfg)

        config = configs[0]
        results = dict()
    
        # ---------------------------------------------------------
        # Load dataset metadata and create validation dataframe
        # ---------------------------------------------------------

        # Different datasets have different metadata file structures
        if down_task == "HumBugDB":
            train_df = pd.read_csv(f"{BEANS_ROOT_PATH}/data/{down_task}/data/metadata/train.csv")
            val_df = pd.read_csv(f"{BEANS_ROOT_PATH}/data/{down_task}/data/metadata/test.csv")
        
        elif down_task == "speech_commands":
            train_df = pd.read_csv(f"{BEANS_ROOT_PATH}/data/{down_task}/train.csv")
            val_df = pd.read_csv(f"{BEANS_ROOT_PATH}/data/{down_task}/test.csv")
        
        else:
            train_df = pd.read_csv(f"{BEANS_ROOT_PATH}/data/{down_task}/annotations.train.csv")
            val_df = pd.read_csv(f"{BEANS_ROOT_PATH}/data/{down_task}/annotations.test.csv")

        # ---------------------------------------------------------
        # Prepare label mapping
        # ---------------------------------------------------------
        class_names = sorted(list(set(train_df.label.tolist())))

        # Convert label names into numeric label indices
        val_df['labels'] = val_df['label'].apply(lambda x: class_names.index(x))
        val_df["filepath"] = val_df["path"].apply(lambda x: f"{BEANS_ROOT_PATH}/{x}")

        config.train.label_map = {class_names[i]: i for i in range(len(class_names))}
        config.train.num_classes = len(class_names)

        # Convert pandas dataframe to HuggingFace Dataset
        val_data = Dataset.from_pandas(val_df)
    
        # ---------------------------------------------------------
        # Convert labels to N-hot format
        # ---------------------------------------------------------
        val_data = val_data.map(
        partial(to_n_hot,
                num_classes=config.train.num_classes,
                ),
        batched=True,
        batch_size=300,
        load_from_cache_file=False,
        num_proc=1,
        )

        # ---------------------------------------------------------
        # Define validation transformation pipeline
        # ---------------------------------------------------------
        val_transform = ValTransformBeans(
        config=config,
        train=False,
        event_decoder=EventDecoder(extracted_interval=config.event_decoder.val.extracted_interval,
                                   sample_rate=config.frontend.sample_rate)
        )

        val_data.set_transform(val_transform)

        # ---------------------------------------------------------
        # Create PyTorch DataLoader for validation dataset
        # ---------------------------------------------------------
        val_loader = torch.utils.data.DataLoader(
            val_data,
            num_workers=config.train.num_workers,
            batch_size=config.train.batch_size,
            drop_last=False,
            shuffle=False
        )
    
        # Map class names to label IDs using the config label map
        label2id = {k: v for k, v in configs[0].train.label_map.items()}

        # Only test on classes relevant for the current dataset
        relevant = [label2id[c] for c in class_names]

        # Store metrics for each model (for later averaging)
        metrics = {
                   "top1_acc": []
        }

        # ---------------------------------------------------------
        # test each model on the test dataset
        # ---------------------------------------------------------
        for model, _ in zip(models, configs):
            # Run evaluation
            _, _, top1_acc = test(model, val_loader, relevant, center_5s=False, device=device)

            # Store metrics
            metrics["top1_acc"].append(top1_acc)

        # ---------------------------------------------------------
        # Aggregate metrics across all checkpoints/models
        # ---------------------------------------------------------
        results[down_task] = {key: float(np.mean(values)) for key, values in metrics.items()}
        print(results)

        # One value per checkpoint, in the order given (seed 1, 2, 3)
        return metrics["top1_acc"]

In [5]:
def load_json_dataset(json_path, config, labels, unknown_label=None, window_width=2, window_shift=1):
    # Open the JSON dataset file (each line contains one audio sample description)
    with open(json_path) as f:
        xs = []
        ys = []
        # Iterate through each line (one recording per line)
        for line in f:
            data = json.loads(line)

            # Path to the audio file
            wav_path = data['path']

            # Total duration of the recording
            length = data['length']

            # Compute how many sliding windows can be extracted
            num_windows = int((length - window_width) / window_shift) + 1

            # ---------------------------------------------------------
            # Slide a window across the audio recording
            # ---------------------------------------------------------
            for window_id in range(num_windows):
                # Compute start and end time of the window
                st, ed = window_id * window_shift, window_id * window_shift + window_width
                # Store window boundaries
                offset_st, offset_ed = st, ed
                # Save input sample (audio path + time window)
                xs.append((wav_path, offset_st, offset_ed))
                # Initialize label vector (multi-label classification)
                y = torch.zeros(len(labels))

                # ---------------------------------------------------------
                # Check overlap between window and annotated events
                # --------------------------------------------------------
                for anon in data['annotations']:
                    if anon['label'] not in labels:
                        if unknown_label is not None:
                            # Assign unknown labels to a predefined class
                            label_id = labels.index(unknown_label)
                        else:
                           raise KeyError(f"Unknown label: {anon['label']}")
                    else:
                        # Get class index
                        label_id = labels.index(anon['label'])

                    # ---------------------------------------------------------
                    # Check if annotation overlaps with the current window
                    # ---------------------------------------------------------

                    # Case 1: annotation start or end falls inside the window
                    if (st <= anon['st'] <= ed) or (st <= anon['ed'] <= ed):
                        denom = min(ed - st, anon['ed'] - anon['st'])
                        if denom == 0:
                            continue
                        overlap = (min(ed, anon['ed']) - max(st, anon['st'])) / denom
                        if overlap > .2:
                            y[label_id] = 1

                    # Case 2: annotation fully contains the window
                    if anon['st'] <= st and ed <= anon['ed']:
                        y[label_id] = 1
                # Save label vector for this window
                ys.append(y)
    return xs, ys

In [6]:
def evaluate_beans_detection(ckpts, down_task, device='cuda'):
        models = []
        configs = []

        # ---------------------------------------------------------
        # Load models and their configs from checkpoints
        # ---------------------------------------------------------
        for ckpt in ckpts:
            m, cfg = load_model(ckpt, device=device)
            models.append(m)
            cfg.train.dataset_name = down_task
            configs.append(cfg)

        config = configs[0]
        results = dict()

        # ---------------------------------------------------------
        # Define dataset-specific parameters
        # source: https://github.com/earthspecies/beans/blob/main/datasets.yml
        # ---------------------------------------------------------
        if down_task == "enabirds":
            labels = ["AMCR", "AMGO", "AMRE", "AMRO", "BAWW", "BCCH", "BGGN", "BHCO", "BHVI", "BLJA", "BTNW", "BWWA",
                     "CARW", "COYE", "EATO", "HETH", "HOWA", "KEWA", "LOWA", "NOCA", "NOFL", "OVEN", "RBGR", "RBWO",
                     "RCKI", "REVI", "SCTA", "SWTH", "TUTI", "WBNU", "WITU", "WOTH", "YBCU", "OTHR"]
            unknown_label = "OTHR"
            window_size = 2
            window_shift = 1

        elif down_task == "hiceas":
            labels =  [1]
            unknown_label = None
            window_size = 10 
            window_shift = 5

        elif down_task == "rfcx":
            labels = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]
            unknown_label = None
            window_size = 10
            window_shift = 5

        elif down_task == "hainan_gibbons":
            labels= [1, 2, 3]
            unknown_label= 1
            window_size = 4
            window_shift= 2


        config.train.num_classes = len(labels)

        # ---------------------------------------------------------
        # Load test dataset from JSON annotations
        # ---------------------------------------------------------
        val_xs, val_ys = load_json_dataset(f"{BEANS_ROOT_PATH}/data/{down_task}/test.jsonl", config, labels, unknown_label, window_size, window_shift)

        # ---------------------------------------------------------
        #  Convert dataset into a pandas-style dictionary
        # ---------------------------------------------------------
        val_df = {"filepath": [], "labels": [], "start_time": [], "end_time": []}
        for i, item in enumerate(val_xs):
            val_df['filepath'].append(f"{BEANS_ROOT_PATH}/{item[0]}")
            val_df['start_time'].append(item[1])
            val_df['end_time'].append(item[2])
            val_df['labels'].append(val_ys[i].numpy())
            
        # Convert dictionary to HuggingFace Dataset
        val_data = Dataset.from_pandas(pd.DataFrame.from_dict(val_df))

        config.train.label_map = {labels[i]: i for i in range(len(labels))}

        # ---------------------------------------------------------
        # Create validation transform pipeline
        # ---------------------------------------------------------
        val_transform = ValTransformBeans(
        config=config,
        train=False,
        event_decoder=EventDecoder(extracted_interval=config.event_decoder.val.extracted_interval,
                                   sample_rate=config.frontend.sample_rate)
        )

        val_data.set_transform(val_transform)

        # ---------------------------------------------------------
        # Create PyTorch DataLoader
        # ---------------------------------------------------------
        val_loader = torch.utils.data.DataLoader(
            val_data,
            num_workers=config.train.num_workers,
            batch_size=config.train.batch_size,
            drop_last=False,
            shuffle=False
        )
    
        # Map class names to label IDs using the config label map
        label2id = {k: v for k, v in configs[0].train.label_map.items()}

        # Only test on classes relevant for the current dataset
        relevant = [label2id[c] for c in labels]

        # Store metrics for each model (for later averaging)
        metrics = {
                   "cmap": [],
                   }

        # ---------------------------------------------------------
        # test each model on the test dataset
        # ---------------------------------------------------------
        for model, _ in zip(models, configs):
            # Run evaluation
            _, cmap, _ = test(model, val_loader, relevant, center_5s=False, device=device)

            # Store metrics
            metrics["cmap"].append(cmap)

        # ---------------------------------------------------------
        # Aggregate metrics across all checkpoints/models
        # ---------------------------------------------------------
        results[down_task] = {key: float(np.mean(values)) for key, values in metrics.items()}
        print(results)

        # One value per checkpoint, in the order given (seed 1, 2, 3)
        return metrics["cmap"]

## Tasks scored by top-1 accuracy (T1-Acc)

In [7]:
# watkins (T1-Acc)
RESULTS["watkins"] = evaluate_beans_classification(seed_dirs("watkins"), TASKS["watkins"][0], device=DEVICE)

Testing: 100%|██████████| 6/6 [00:04<00:00,  1.28it/s]
Testing: 100%|██████████| 6/6 [00:04<00:00,  1.34it/s]
Testing: 100%|██████████| 6/6 [00:04<00:00,  1.32it/s]
{'watkins': {'top1_acc': 0.8485742410024008}}

Map: 100%|██████████| 339/339 [00:00<00:00, 105668.03 examples/s]

In [8]:
# bats (T1-Acc)
RESULTS["bats"] = evaluate_beans_classification(seed_dirs("bats"), TASKS["bats"][0], device=DEVICE)

Testing: 100%|██████████| 32/32 [00:48<00:00,  1.52s/it]
Testing: 100%|██████████| 32/32 [00:49<00:00,  1.53s/it]
Testing: 100%|██████████| 32/32 [00:48<00:00,  1.51s/it]
{'egyptian_fruit_bats': {'top1_acc': 0.8038333257039388}}

Map: 100%|██████████| 2000/2000 [00:00<00:00, 218886.55 examples/s]

In [9]:
# cbi (T1-Acc)
RESULTS["cbi"] = evaluate_beans_classification(seed_dirs("cbi"), TASKS["cbi"][0], device=DEVICE)

Testing: 100%|██████████| 57/57 [00:39<00:00,  1.44it/s]
Testing: 100%|██████████| 57/57 [00:39<00:00,  1.43it/s]
Testing: 100%|██████████| 57/57 [00:39<00:00,  1.44it/s]
{'cbi': {'top1_acc': 0.8146408796310425}}

Map: 100%|██████████| 3620/3620 [00:00<00:00, 140397.06 examples/s]

In [10]:
# dogs (T1-Acc)
RESULTS["dogs"] = evaluate_beans_classification(seed_dirs("dogs"), TASKS["dogs"][0], device=DEVICE)

Testing: 100%|██████████| 3/3 [00:06<00:00,  2.21s/it]
Testing: 100%|██████████| 3/3 [00:06<00:00,  2.22s/it]
Testing: 100%|██████████| 3/3 [00:06<00:00,  2.21s/it]
{'dogs': {'top1_acc': 0.9736210902531942}}

Map: 100%|██████████| 139/139 [00:00<00:00, 65301.10 examples/s]

In [11]:
# humbugdb (T1-Acc)
RESULTS["humbugdb"] = evaluate_beans_classification(seed_dirs("humbugdb"), TASKS["humbugdb"][0], device=DEVICE)

Testing: 100%|██████████| 30/30 [00:25<00:00,  1.20it/s]
Testing: 100%|██████████| 30/30 [00:24<00:00,  1.20it/s]
Testing: 100%|██████████| 30/30 [00:24<00:00,  1.21it/s]
{'HumBugDB': {'top1_acc': 0.7964855631192526}}

Map: 100%|██████████| 1859/1859 [00:00<00:00, 216505.00 examples/s]

In [12]:
# speech (T1-Acc)
RESULTS["speech"] = evaluate_beans_classification(seed_dirs("speech"), TASKS["speech"][0], device=DEVICE)

Testing: 100%|██████████| 172/172 [00:14<00:00, 11.66it/s]
Testing: 100%|██████████| 172/172 [00:14<00:00, 11.64it/s]
Testing: 100%|██████████| 172/172 [00:14<00:00, 11.69it/s]
{'speech_commands': {'top1_acc': 0.8613357543945312}}

Map: 100%|██████████| 11005/11005 [00:00<00:00, 266473.74 examples/s]

## Tasks scored by class-wise mean average precision (cmAP)

In [13]:
# enabirds (cmAP)
RESULTS["enabirds"] = evaluate_beans_detection(seed_dirs("enabirds"), TASKS["enabirds"][0], device=DEVICE)

Testing: 100%|██████████| 71/71 [00:12<00:00,  5.52it/s]
Testing: 100%|██████████| 71/71 [00:12<00:00,  5.58it/s]
Testing: 100%|██████████| 71/71 [00:12<00:00,  5.64it/s]
{'enabirds': {'cmap': 0.7622098422085437}}

In [14]:
# hiceas (cmAP)
RESULTS["hiceas"] = evaluate_beans_detection(seed_dirs("hiceas"), TASKS["hiceas"][0], device=DEVICE)

Testing: 100%|██████████| 24/24 [00:18<00:00,  1.32it/s]
Testing: 100%|██████████| 24/24 [00:17<00:00,  1.34it/s]
Testing: 100%|██████████| 24/24 [00:18<00:00,  1.32it/s]
{'hiceas': {'cmap': 0.5906908043817117}}

In [15]:
# rfcx (cmAP)
RESULTS["rfcx"] = evaluate_beans_detection(seed_dirs("rfcx"), TASKS["rfcx"][0], device=DEVICE)

Testing: 100%|██████████| 163/163 [02:01<00:00,  1.34it/s]
Testing: 100%|██████████| 163/163 [02:01<00:00,  1.35it/s]
Testing: 100%|██████████| 163/163 [02:02<00:00,  1.33it/s]
{'rfcx': {'cmap': 0.19981443127507256}}

In [16]:
# hainan_gibbons (cmAP)
RESULTS["hainan_gibbons"] = evaluate_beans_detection(seed_dirs("hainan_gibbons"), TASKS["hainan_gibbons"][0], device=DEVICE)

Testing: 100%|██████████| 290/290 [00:29<00:00,  9.71it/s]
Testing: 100%|██████████| 290/290 [00:29<00:00,  9.79it/s]
Testing: 100%|██████████| 290/290 [00:29<00:00,  9.75it/s]
{'hainan_gibbons': {'cmap': 0.5481363428929867}}

## Results

Per-seed scores with their mean and sample standard deviation. The last row of each table averages its tasks within each seed.

### Tasks scored by top-1 accuracy (T1-Acc)

In [17]:
def results_table(metric):
    """Per-seed scores for the tasks of one metric, with their mean and sample std."""
    seeds = pd.DataFrame({task: RESULTS[task] for task, (_, m) in TASKS.items() if m == metric},
                         index=["seed 1", "seed 2", "seed 3"]).T
    # Mean over tasks, computed within each seed
    seeds.loc[f"mean ({metric})"] = seeds.mean()
    table = seeds.assign(mean=seeds.mean(axis=1), std=seeds.std(axis=1, ddof=1))
    table.index.name = "task"
    return table.round(3)

results_table("T1-Acc")

               seed 1  seed 2  seed 3   mean    std
task
watkins         0.858   0.850   0.838  0.849  0.010
bats            0.801   0.803   0.807  0.804  0.003
cbi             0.815   0.815   0.814  0.815  0.001
dogs            0.986   0.971   0.964  0.974  0.011
humbugdb        0.799   0.792   0.799  0.796  0.004
speech          0.861   0.863   0.860  0.861  0.002
mean (T1-Acc)   0.853   0.849   0.847  0.850  0.003

### Tasks scored by class-wise mean average precision (cmAP)

In [18]:
results_table("cmAP")

                seed 1  seed 2  seed 3   mean    std
task
enabirds         0.761   0.764   0.762  0.762  0.001
hiceas           0.585   0.586   0.601  0.591  0.009
rfcx             0.198   0.201   0.201  0.200  0.002
hainan_gibbons   0.542   0.570   0.533  0.548  0.019
mean (cmAP)      0.521   0.530   0.524  0.525  0.005